### ISSUE TITLE
Orbis Unjailed Store-R2.pkg

### ISSUE THREAD

**Issue by chipsnblip** [florinsdistortedvision/florinsdistortedvision#1]
hi florin. i'm new to the ps4 scene and have a quick question regarding your Orbis Unjailed wiki project.  i was going to open an issue there, but the feature seems to be unavailable.  it has to do with the Homebrew Store page: https://florinsdistortedvision.github.io/orbisunjailed/hb-store/

the download link (https://pkg-zone.com/Store-R2.pkg) references a pkg file, but the payload is actually a file named 'Store-R2.dist'. is that intended, or cause for alarm?  sorry if it's poor etiquette to be bugging you here, i don't have a twitter account and couldn't find another way to get a hold of you.

thanks.

**Comment by florinsdistortedvision** [comment]
hi, no worries, the download link does download a pkg not a dist, so it may be a issue with whatever device you're downloading from. The link is from pkg-zone direct link

**Comment by chipsnblip** [comment]
interesting. ok, so i disabled pihole and retried the download, and got the .pkg this time.  the files are identical:

$ sha256sum Store-R2.*
e765f807fe2d8db639d5e953cebb82e14171e6aaa6c25df75635a777f97f26c1  Store-R2.dist
e765f807fe2d8db639d5e953cebb82e14171e6aaa6c25df75635a777f97f26c1  Store-R2.pkg

looks like the pihole is to blame here..

anyway, thanks for your contributions and happy new year!
